### ISSUE TITLE
Unable to load modules in Slicer 4.5 release / OS X

### ISSUE THREAD

**Issue by ihnorton** [NIRALUser/DTIProcessToolkit#14]
There are loading errors listed in the log [1] on startup, after installing `DTIProcess` from the Extension Manager in the Slicer 4.5.1 release build on OS X. It seems to be a framework linking issue, possibly requires some updates to the CMake files? (as in [this bug](http://www.na-mic.org/Bug/view.php?id=3982) and [related commit](https://github.com/pnlbwh/ukftractography/commit/3d24f89a045ba25a661a5ca93912b348ce0345c6#diff-29a0e2dfc1dab25c907b016698e54300R1))

cc @jcfr

[1]

```
  Error(s):
    CLI executable: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/dtiaverage
    dyld: Library not loaded: @rpath/lib/Slicer-4.5/libvtkIO-6.3.1.dylib
  Referenced from: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/dtiaverage
  Reason: image not found

    CLI executable: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/dtiaverage
    Failed to retrieve Xml Description
Fail to instantiate module "dtiaverage" 
  Error(s):
    CLI executable: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/dtiestim
    dyld: Library not loaded: @rpath/lib/Slicer-4.5/libITKPath-4.8.1.dylib
  Referenced from: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/dtiestim
  Reason: image not found

    CLI executable: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/dtiestim
    Failed to retrieve Xml Description
Fail to instantiate module "dtiestim" 
  Error(s):
    CLI executable: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/dtiprocess
    dyld: Library not loaded: @rpath/lib/Slicer-4.5/libITKPath-4.8.1.dylib
  Referenced from: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/dtiprocess
  Reason: image not found

    CLI executable: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/dtiprocess
    Failed to retrieve Xml Description
Fail to instantiate module "dtiprocess" 
  Error(s):
    CLI executable: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/fiberprocess
    dyld: Library not loaded: @rpath/lib/Slicer-4.5/libvtkIO-6.3.1.dylib
  Referenced from: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/fiberprocess
  Reason: image not found

    CLI executable: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/fiberprocess
    Failed to retrieve Xml Description
Fail to instantiate module "fiberprocess" 
  Error(s):
    CLI executable: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/fiberstats
    dyld: Library not loaded: @rpath/lib/Slicer-4.5/libvtkIO-6.3.1.dylib
  Referenced from: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/fiberstats
  Reason: image not found

    CLI executable: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/fiberstats
    Failed to retrieve Xml Description
Fail to instantiate module "fiberstats" 
  Error(s):
    CLI executable: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/polydatamerge
    dyld: Library not loaded: @rpath/lib/Slicer-4.5/libITKCommon-4.8.1.dylib
  Referenced from: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/polydatamerge
  Reason: image not found

    CLI executable: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/polydatamerge
    Failed to retrieve Xml Description
Fail to instantiate module "polydatamerge" 
  Error(s):
    CLI executable: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/polydatatransform
    dyld: Library not loaded: @rpath/lib/Slicer-4.5/libITKCommon-4.8.1.dylib
  Referenced from: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/polydatatransform
  Reason: image not found
    CLI executable: /Applications/Slicer 4.5.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules/polydatatransform
    Failed to retrieve Xml Description
Fail to instantiate module "polydatatransform" 
```

**Comment by jcfr** [comment]
Using `otool -L`, we can the path to dependencies are correct:

```
factory@kitware:/Users/kitware/Dashboards/Nightly/S-450-E-b/DTIProcess-build/_CPack_Packages/Darwin/TGZ/24735-macosx-amd64-DTIProcess-git8205274-2015-10-23/Slicer.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules> otool -L polydatamerge
polydatamerge:
        @rpath/lib/Slicer-4.5/libITKCommon-4.8.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        @rpath/lib/Slicer-4.5/libitksys-4.8.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        @rpath/lib/Slicer-4.5/libitkvnl_algo-4.8.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        @rpath/lib/Slicer-4.5/libitkvnl-4.8.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        @rpath/lib/Slicer-4.5/libitkv3p_netlib-4.8.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        @rpath/lib/Slicer-4.5/libITKIOImageBase-4.8.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        @rpath/lib/Slicer-4.5/libITKIOGDCM-4.8.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        @rpath/lib/Slicer-4.5/libitkgdcmDICT-4.8.1.dylib (compatibility version 1.0.0, current version 1.0.0)
[...]
```

That said, the `rpath` are not set in the DTIProcess CLIs. For comparison, here is the output of `otool -l` against SkullStripper:

```
factory@kitware:/Users/kitware/Dashboards/Nightly/S-450-E-b/SkullStripper-build/_CPack_Packages/Darwin/TGZ/24735-macosx-amd64-SkullStripper-git280121d-2015-01-12/Slicer.app/Contents/Extensions-24735/SkullStripper/lib/Slicer-4.5/cli-modules> otool -l SkullStripper | grep -A 3 LC_RPATH | grep path
         path @loader_path/../../../ (offset 12)
         path @loader_path/../../../../../ (offset 12)
         path /Users/kitware/Dashboards/Package/Slicer-450-package/teem-build/bin (offset 12)
         path /Users/kitware/Dashboards/Package/Slicer-450-package/OpenIGTLink-build/bin (offset 12)
```

and against `polydatamerge`:

```
factory@kitware:/Users/kitware/Dashboards/Nightly/S-450-E-b/DTIProcess-build/_CPack_Packages/Darwin/TGZ/24735-macosx-amd64-DTIProcess-git8205274-2015-10-23/Slicer.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules> otool -l polydatamerge | grep -A 3 LC_RPATH | grep path
```

=> No output



### Why is this happening ?

Let's try to find out.

`DTIProcessToolkit` is a superbuild extension and it builds its own flavor of `SlicerExecutionModel` project. See [here](https://github.com/NIRALUser/DTIProcessToolkit/blob/af6b0940e3c31647d50b35b74943ec143115b6c2/SuperBuild/External_SlicerExecutionModel.cmake)

That lead to few questions:

1. When `DTIProcessToolkit` is build as a Slicer extension (vs Standalone), which version of `SlicerExecutionModel` is used ?

2. If the custom `SlicerExecutionModel` is used to build the extension .. is the `SlicerExecutionModel_DEFAULT_CLI_EXECUTABLE_LINK_FLAGS` properly set ? For example, see [here](https://github.com/Slicer/Slicer/blob/f0d45cdd464448d21bd99a2d7859b773f5f138a0/SuperBuild/External_SlicerExecutionModel.cmake#L25) to see the value used for regular Slicer modules.


Answer to question 1 is most likely __YES__. As we can see [here](https://github.com/NIRALUser/DTIProcessToolkit/blob/af6b0940e3c31647d50b35b74943ec143115b6c2/SuperBuild.cmake#L35), a custom flavor of `SlicerExecutionModel` is used when `DTIProcess_BUILD_SLICER_EXTENSION` is `TRUE`.

Answer to question 2 is __NO__. Inspecting [External_SlicerExecutionModel.cmake](https://github.com/NIRALUser/DTIProcessToolkit/blob/af6b0940e3c31647d50b35b74943ec143115b6c2/SuperBuild/External_SlicerExecutionModel.cmake) or grep-ing for `loader_path` in the `DTIProcessToolkit` code base doesn't lead to anything. 

### How to move forward ?

That lead to the following new questions:

1. Would it be sufficient to update the `DTIProcessToolkit` copy of `External_SlicerExecutionModel.cmake` to properly set `SlicerExecutionModel_DEFAULT_CLI_EXECUTABLE_LINK_FLAGS` ?

2. How to prevent such issue from happening again ?

3. Why `DTIProcessToolkit` is not using the library build by Slicer when  `DTIProcess_BUILD_SLICER_EXTENSION` is `TRUE`

#### Answer question 1

I will follow up with this in an other comment.

#### Answer question 2

Not an easy answer. The strength of external projects is to allow building custom flavor of project ... 

One observation is that external project maintained in [Slicer](https://github.com/Slicer/Slicer/tree/master/SuperBuild), the one maintained in [BRAINSia/NAMICExternalProjects](https://github.com/BRAINSia/NAMICExternalProjects) and the one in [this](https://github.com/NIRALUser/DTIProcessToolkit/tree/af6b0940e3c31647d50b35b74943ec143115b6c2/SuperBuild) project are all different. 

Option to move forward could be to:
* minimize difference following the same convention.
* improve upstream project allowing runtime modularity
* facilitate integration of patched upstream

We could also improve `SlicerExecutionModel` to remove dependency on ITK and/or VTK.

#### Answer question 3

May be it is because it build either ITK or VTK statically so that it can enable/disable some different option. Though I couldn't find evidence of this inspecting the `DTIProcessToolkit` [ITK](https://github.com/NIRALUser/DTIProcessToolkit/blob/af6b0940e3c31647d50b35b74943ec143115b6c2/SuperBuild/External_ITKv4.cmake) or [VTK](https://github.com/NIRALUser/DTIProcessToolkit/blob/af6b0940e3c31647d50b35b74943ec143115b6c2/SuperBuild/External_VTK.cmake) external projects.

May be @fbudin69500 could chime in ...

**Comment by jcfr** [comment]
Reading commit message associated with Slicer [r22023](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=22023) will also provide more context.

**Comment by jcfr** [comment]
Seems there are two types of CLIs:

1.  the one build directly in `DTIProcessToolkit` (ie `dtiprocess`): https://github.com/NIRALUser/DTIProcessToolkit/tree/af6b0940e3c31647d50b35b74943ec143115b6c2/Applications

2. the one coming from the `niral_utilities` project (ie `polydatamerge`): https://github.com/NIRALUser/niral_utilities


For the case 1, the `rpath` is properly set in the build tree:

```
factory@kitware:/Users/kitware/Dashboards/Nightly/S-450-E-b/DTIProcess-build/_CPack_Packages/Darwin/TGZ/24735-macosx-amd64-DTIProcess-git8205274-2015-10-23/Slicer.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules> otool -l dtiprocess | grep -A3 LC_RPATH | grep path
         path @loader_path/../../../ (offset 12)
```

For the case 2, it is is not the case (as shown above):

```
factory@kitware:/Users/kitware/Dashboards/Nightly/S-450-E-b/DTIProcess-build/_CPack_Packages/Darwin/TGZ/24735-macosx-amd64-DTIProcess-git8205274-2015-10-23/Slicer.app/Contents/Extensions-24735/DTIProcess/lib/Slicer-4.5/cli-modules> otool -l polydatamerge | grep -A 3 LC_RPATH | grep path
```

**Comment by jcfr** [comment]
In case of regular Slicer extension, the rpath is specifically set in `UseSlicer`. See https://github.com/Slicer/Slicer/blob/f0d45cdd464448d21bd99a2d7859b773f5f138a0/CMake/UseSlicer.cmake.in#L312-L315

**Comment by jcfr** [comment]
@ihnorton See #15 which fixes the issue for all CLIs built within the [Applications](https://github.com/NIRALUser/DTIProcessToolkit/tree/master/Applications) folder.

To address the problem for all executables, the executable from [niral_utilities](https://github.com/NIRALUser/niral_utilities) would have to be updated to use the macro `SEMMacroBuildCLI`. Example of usage are [available](https://github.com/Slicer/Slicer/blob/master/Extensions/Testing/CLIExtensionTemplate/CLIModuleTemplate/CMakeLists.txt) in Slicer.

I also provided some direction as comment in the code and in the commit message of https://github.com/jcfr/DTIProcessToolkit/commit/617591f1291f0ad28228304718f641cc15ad7a5f

Cc: @juanprietob

**Comment by juanprietob** [comment]
Are you referring to https://github.com/NIRALUser/niral_utilities/blob/master/PolydataMerge/CMakeLists.txt#L31 ?
Instead of `GenerateCLP` change it to `SEMMacroBuildCLI`?

**Comment by jcfr** [comment]
@juanprietob Exactly, that is the general idea. That project need to be modernized.

**Comment by juanprietob** [comment]
I'm having this error while I try to build the `DTIProcess` extension

`ld: file not found: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList for architecture x86_64`

I am using cmake version 3.3.20150908-g70ea1
xcode Version 7.1.1 (7B1005)

Any clues?

**Comment by juanprietob** [comment]
I have update it [NiralUtilities](https://github.com/NIRALUser/niral_utilities), [DTIProcessToolkit](git@github.com:NIRALUser/DTIProcessToolkit.git) and generated the pull request for the [extension index](https://github.com/Slicer/ExtensionsIndex/pull/1208). 

NiralUtilities uses the SEMMacroBuild to generate the executables and includes the SlicerExecutionModelPackage.

**Comment by juanprietob** [comment]
@jcfr 
Hello, this issue still persist. 
The variables:

`    -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
    -DCMAKE_OSX_SYSROOT=${CMAKE_OSX_SYSROOT}
    -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}`

Are not passed down from the external project when building in APPLE -> [Superbuild.cmake](https://github.com/NIRALUser/DTIProcessToolkit/blob/master/SuperBuild.cmake#L94-L99)

**Comment by jcfr** [comment]
@juanprietob 

Could you confirm that the top-level project have the `CMAKE_OSX_*` variable properly set ? If not,  that would explain why they are not passed to the sub project.

Will the following steps reproduce the problem ?

```
git clone git@github.com:NIRALUser/DTIProcessToolkit.git
mkdir DTIProcessToolkit-build
cd DTIProcessToolkit-build
cmake -DSlicer_DIR=/path/to/Slicer-SuperBuild/Slicer-build -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_OSX_SYSROOT=<sdkroot> -DCMAKE_OSX_DEPLOYMENT_TARGET=<deploy-target> ../DTIProcessToolkit
make -j9
```

where `<sdkroot>` and `<deploy-target>` are identical to the one used in Slicer.

**Comment by juanprietob** [comment]
This happens when built as an extension.
To configure the project:
`cmake -DSlicer_DIR:PATH=${SLICER}/bin/Slicer-build -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DSlicer_EXTENSION_DESCRIPTION_DIR:PATH=../ExtensionsIndexTemp  $SLICER/Extensions/CMake/`

Where directory `ExtensionsIndexTemp` contains `DTIProcess.s4ext`

Variables `CMAKE_OSX_SYSROOT` and `CMAKE_OSX_ARCHITECTURES` are empty in the `DTIProcess-build` directory.

**Comment by jcfr** [comment]
Thanks for looking into the issue.

It turns there is a bug with the system building the ExtensionsIndex.

Could you apply the following patch on your current Slicer source tree: 

  https://github.com/jcfr/Slicer/tree/fix-extensionindex-build-on-macosx

There are no need to rebuild Slicer, applying the patch and doing a clean build of the index should be enough.

Thanks for your help,

**Comment by juanprietob** [comment]
The fix does solve the issue but I found a new one.

DTIProcessToolkit builds [niral_utilities](https://github.com/NIRALUser/niral_utilities), i.e., 
DTIProcessToolkit-build/DTIProcess-build/niral_utilities-build

niral_utilities [was modernized](https://github.com/NIRALUser/niral_utilities/pull/6) to use the macro [SEMMacroBuildCLI](https://github.com/Slicer/SlicerExecutionModel/blob/master/CMake/SEMMacroBuildCLI.cmake)

There is a configuration error when executing the macro. The variables `INSTALL_RUNTIME_DESTINATION` and `INSTALL_LIBRARY_DESTINATION` are empty in DTIProcessToolkit/DTIProcess-build/niral_utilities-build/CMakeCache.txt
However, both variables are set when looking at the configuration 
DTIProcessToolkit/DTIProcess-build/CMakeCache.txt


`cat  ./DTIProcessToolkit-build/DTIProcess-build/CMakeCache.txt | grep INSTALL_RUNTIME_DESTINATION 

INSTALL_RUNTIME_DESTINATION:PATH=bin`

`cat  ./DTIProcessToolkit-build/DTIProcess-build/niral_utilities-build/CMakeCache.txt | grep INSTALL_RUNTIME_DESTINATION

'

**Comment by ihnorton** [comment]
@juanprietob it looks like several NIRAL extensions are still failing build for similar reasons.

http://slicer.cdash.org/index.php?subproject=DTIPrep&project=Slicer4
http://slicer.cdash.org/index.php?subproject=DTIProcess&project=Slicer4
http://slicer.cdash.org/index.php?subproject=DTIAtlasBuilder&project=Slicer4

Did you have any luck with updating for CMake changes?

**Comment by juanprietob** [comment]
@ihnorton I am trying to replicate the errors. 
I believe to have fixed the DTIProcess extension. However, DTIAtlasBuilder depends on DTI-Reg which depends on DTIProcess. During building of DTI-Reg, the extension tries to load the file `DTIProcess-exports.cmake` which does not exist. Do you know how is this file generated? What should I add to DTIProcess cmake?

**Comment by ihnorton** [comment]
Hi @juanprietob, just wanted to see if there was any update on this? We are interested in using DTIPrep and other tools as extensions in the Slicer nightly. It looks like there is a new issue that some of these modules have hard-coded the VTK version, so they are failing now that Slicer superbuild has updated to VTKv7. Thanks!

**Comment by juanprietob** [comment]
Hi @ihnorton I will make the necessary fixes for VTKv7

**Comment by juanprietob** [comment]
Hello @jcfr, I need some help with the DTIPrep extension. There is an error in the upload step. It is trying to find a file named `packageupload_cpack_output.txt`. Do you know who how to create this file?

**Comment by juanprietob** [comment]
This extension is compiling with the latest ITK and VTK versions used in Slicer
