### ISSUE TITLE
dtiestim produces bad DTI results

### ISSUE THREAD

**Issue by hjmjohnson** [NIRALUser/DTIProcessToolkit#32]
@juanprietob @fbudin69500 @styner,

There appears to be bug in the dtiestim program.  I am consistently getting bad results for all uses of dtiestim.

The following picture shows that tensors are only estimated in places of CSF, and that white matter completely excluded and set to zero.  It seems to be some type of thresholding bug.

![image](https://cloud.githubusercontent.com/assets/313970/21081086/c4aa06b8-bf84-11e6-8e0c-82c11e7596ea.png)

When comparing dtiestim to Slicers built in tools, or FSL's dti analysis tools, dtiestim always gives bad results.  See the attached script for the command line options.

[SlicerDWIProcessing.sh.zip](https://github.com/NIRALUser/DTIProcessToolkit/files/644534/SlicerDWIProcessing.sh.zip)

**Comment by fbudin69500** [comment]
@hjmjohnson I do not work on these tools anymore now that I work at Kitware, but have you tried to change the value of the threshold ([threshold/baselineThreshold](https://github.com/NIRALUser/DTIProcessToolkit/blob/master/Applications/dtiestim.xml#L108)) which by default uses an Otsu filter to detect what to threshold. Maybe if you set it to 0?

**Comment by styner** [comment]
Francois is correct. That has been the default behavior of dtiestim since the start, but I am thinking we probably need to change that (though I don't like changing API's but rather want to be backwards compatible). In all my scripts a call to dtiestim with -t 0 is the norm. It is important to note that dtiestim will even apply and Otsu based threshold when a brain mask is specified and it basically does two masking operations, one based on the specified mask and another based on the otsu thresholding.

**Comment by hjmjohnson** [comment]
@styner @fbudin69500 Thank you for the quick response.  I feel silly now.  I missed that option in dtiestim.

Hans

**Comment by juanprietob** [comment]
Should this issue be closed, or change the default settings?

**Comment by styner** [comment]
We’ll work on it for the next version. We anyway need to add/debug several things in the next month.
Martin

**Comment by hjmjohnson** [comment]
Thank you.  I always appreciate your willingness to make these tools better.

Hans
